definitions:
  entity.SignInInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  entity.SignUpInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 8
        type: string
      passwordConfirm:
        minLength: 8
        type: string
      photo:
        type: string
    required:
    - email
    - name
    - password
    - passwordConfirm
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3000
info:
  contact:
    email: prastiyo.beka12@gmail.com
    name: API Support
  description: This is a NASH API DOCUMENTATION
  termsOfService: http://swagger.io/terms/
  title: API Documentation
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Login to system
      parameters:
      - description: Login Input
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/entity.SignInInput'
      produces:
      - application/json
      responses: {}
      summary: Login System
      tags:
      - Auth System
  /api/auth/sign-up:
    post:
      consumes:
      - application/json
      description: Sign Up
      parameters:
      - description: SignUpInput
        in: body
        name: sign-up
        required: true
        schema:
          $ref: '#/definitions/entity.SignUpInput'
      produces:
      - application/json
      responses: {}
      summary: Sign Up User
      tags:
      - Auth System
  /api/v1/logout:
    post:
      consumes:
      - application/json
      description: Logout to system
      produces:
      - application/json
      responses: {}
      summary: Logout System
      tags:
      - User Credential
  /api/v1/me:
    get:
      consumes:
      - application/json
      description: Ambil data profile user login
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Get Profile
      tags:
      - User Credential
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
